[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fiona>=1.10.1",
    "geopandas>=1.1.1",
    "pandas>=2.3.2",
    "pyproj>=3.7.2",
    "requests>=2.32.5",
    "shapely>=2.1.1",
]
